# Generated by Django 5.2.4 on 2025-08-03 09:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mynewapp', '0003_admin'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='admin',
            name='pssword',
        ),
        migrations.AddField(
            model_name='admin',
            name='password',
            field=models.CharField(default=2, max_length=50),
            preserve_default=False,
        ),
    ]
