# Generated by Django 5.2.4 on 2025-08-06 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mynewapp', '0004_remove_admin_pssword_admin_password'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='address',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='book',
            name='quantity',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='book',
            name='total_price',
            field=models.IntegerField(default=0),
        ),
    ]
