# Generated by Django 5.2.4 on 2025-08-06 11:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mynewapp', '0005_book_address_book_quantity_book_total_price'),
    ]

    operations = [
        migrations.RenameField(
            model_name='book',
            old_name='name',
            new_name='book_name',
        ),
    ]
